/* =========================================================================
   glossary.js — site-wide GLOSSARY
   Each term: definition + deeper technical explanation + real-world example
   + exam relevance. Drawn from CO4–CO8. (Used only by the Glossary tab;
   NOT used by Boss Mode or the topic tests.)
   ========================================================================= */
const GLOSSARY = [
  /* ---------------- CO4 ---------------- */
  { area:'CO4', term:'Legislation vs Regulation', def:'Legislation = laws passed by Parliament; regulation = the rules/bodies that ensure those laws are upheld.', tech:'Acts (e.g. the Data Protection Act 2018) set the legal duties; regulators (e.g. the ICO, HSE) enforce them and can issue penalties.', eg:'The ICO regulates and enforces data-protection legislation by investigating breaches and issuing fines.', exam:'Don\'t confuse the two — a "state the legislation" question wants the Act; the regulator is who enforces it.' },
  { area:'CO4', term:'Health and Safety at Work Act 1974', def:'The main law requiring employers to ensure the health, safety and welfare of everyone affected by their work.', tech:'Imposes duties to provide a safe environment, training, information, supervision and risk assessments — extending to contractors and visitors, not just employees.', eg:'A technician installing ceiling cabling in an occupied office must risk-assess and cordon the area to protect staff below.', exam:'The go-to Act for any installation/workplace scenario; pair it with Working at Height Regulations for ceiling/ladder work.' },
  { area:'CO4', term:'Display Screen Equipment (DSE) Regulations 1992', def:'Regulations protecting people who use screens (PCs, laptops, tablets) for an hour or more at a time.', tech:'Require workstation assessments, regular screen breaks, eye tests on request, and adjustable/ergonomic equipment; apply to home and hybrid workers too.', eg:'An employer issuing laptops must assess home-worker setups and provide an ergonomic chair/footrest on request.', exam:'Use for "health and safety of screen users" questions — name a specific duty (assessment, breaks, eye test).' },
  { area:'CO4', term:'UK GDPR / Data Protection Act 2018', def:'The law controlling how personal data is collected, processed and stored.', tech:'Built on principles: lawfulness/fairness/transparency, purpose limitation, data minimisation, accuracy, storage limitation, integrity & confidentiality, accountability. Breaches reported within 72 hours; fines up to £17.5m or 4% of global turnover.', eg:'A firm must delete customer data once it is no longer needed (storage limitation) and report a serious breach to the ICO within 72 hours.', exam:'Quote a named principle and the 72-hour/fine figures — examiners reward precise recall.' },
  { area:'CO4', term:'Data controller vs data processor', def:'A controller decides why and how personal data is used; a processor handles it on the controller\'s behalf.', tech:'Processors must act only on documented instructions under a Data Processing Agreement (DPA); both can be liable for breaches.', eg:'A shop (controller) uses a cloud payroll provider (processor) to process staff data under a DPA.', exam:'A common 2-marker: "identify who decides how data is used" → the controller.' },
  { area:'CO4', term:'Computer Misuse Act 1990', def:'Law making unauthorised access to and modification of computer material a criminal offence.', tech:'Three core offences: (1) unauthorised access; (2) access with intent to commit a further offence; (3) unauthorised modification (incl. planting a virus). Strengthened by the Serious Crime Act 2015 (malware distribution).', eg:'An employee logging into a colleague\'s account they\'re not authorised to use commits offence (1).', exam:'Be able to match a scenario (e.g. virus) to the correct offence (unauthorised modification).' },
  { area:'CO4', term:'Equality Act 2010', def:'Law protecting people from discrimination across nine protected characteristics.', tech:'Covers direct/indirect discrimination, harassment and victimisation in work, services and education; relevant to unbiased system and AI design.', eg:'An AI hiring tool that disadvantages a protected group could be unlawful indirect discrimination.', exam:'Know the four discrimination types and that IT/AI design must avoid bias.' },
  { area:'CO4', term:'Copyright vs Patent', def:'Copyright automatically protects original works (code, text); a patent protects a new invention.', tech:'Copyright is automatic and lasts decades; patents must be applied for, last up to 20 years, require an inventive step, and cannot cover an algorithm alone.', eg:'Source code is copyrighted on creation; a novel hardware mechanism could be patented.', exam:'"Which IP protection is automatic?" → copyright. "Up to 20 years for an invention?" → patent.' },
  { area:'CO4', term:'Acceptable Use Policy (AUP)', def:'Internal rules users must follow when using an organisation\'s systems.', tech:'Sets permitted/prohibited activities, password rules, communication etiquette and sanctions; underpins Computer Misuse Act enforcement by defining "unauthorised".', eg:'An AUP banning unauthorised USB devices and password sharing, with dismissal as a sanction.', exam:'"What is the purpose of an AUP?" → define authorised use and protect the organisation.' },
  { area:'CO4', term:'ISO/IEC 27001 & WCAG 2.2', def:'27001 is the information-security management standard; WCAG 2.2 is the web-accessibility standard.', tech:'27001 reassures clients an organisation manages information securely; WCAG\'s four principles are Perceivable, Operable, Understandable, Robust (POUR).', eg:'A bank may refuse to contract a supplier that lacks ISO 27001; a public site must meet WCAG for accessibility.', exam:'Remember POUR and that 27001 = security management; PCI DSS = card payments.' },
  { area:'CO4', term:'Whistleblowing', def:'Reporting wrongdoing in the public interest; whistleblowers are legally protected from unfair treatment.', tech:'In software this includes shipping known critical vulnerabilities, hidden backdoors, selling data without consent or releasing biased AI; reportable internally, to a regulator (ICO) or the police.', eg:'A developer reports their employer knowingly shipping software with a security backdoor.', exam:'Identify what counts as a whistleblowing concern and that the person is protected by law.' },

  /* ---------------- CO5 ---------------- */
  { area:'CO5', term:'Stakeholder (internal vs external)', def:'Anyone with an interest in an organisation; internal are inside it, external are outside but affected.', tech:'Internal: owners, directors, employees. External: customers, suppliers, shareholders, investors, government, outsourced services.', eg:'A coffee shop\'s baristas are internal stakeholders; its bean supplier is external.', exam:'"State two external stakeholders" is a frequent 2-marker — don\'t list employees/owners.' },
  { area:'CO5', term:'SME', def:'A Small or Medium-sized Enterprise — fewer than 250 staff (with turnover/balance-sheet limits).', tech:'Part of the private sector; includes sole traders and partnerships through to mid-size companies.', eg:'A 40-person web-design agency is an SME.', exam:'Used to classify organisations by size/sector in business-context questions.' },
  { area:'CO5', term:'Public / Private / Third sector', def:'Private = owned by individuals/firms for profit; public = government-owned, tax-funded; third = non-profit.', tech:'Third sector includes charities, community groups and social enterprises that reinvest profit for a cause.', eg:'NHS (public), Dyson (private), a local food bank (third).', exam:'Know which sector an organisation belongs to and how it\'s funded.' },
  { area:'CO5', term:'KPI (Key Performance Indicator)', def:'A measurable value used to track how well an organisation/area is performing.', tech:'Digital dashboards surface KPIs in real time (sales, conversion rate, retention, downtime) for management decisions.', eg:'A manager monitors "orders fulfilled without errors" as a KPI on a live dashboard.', exam:'Links to how digital systems support the management function.' },
  { area:'CO5', term:'PESTLE', def:'A framework for external factors that drive organisational change: Political, Economic, Social, Technological, Legal, Environmental.', tech:'Used alongside internal triggers (restructuring, expansion, downsizing) to analyse why change is needed.', eg:'A new data-protection law (Legal) forces a company to change how it stores data.', exam:'"State two external factors that could trigger change" → pick PESTLE letters.' },
  { area:'CO5', term:'Change Advisory Board (CAB)', def:'A group of stakeholders that prioritises, reviews, approves and monitors changes.', tech:'Assesses urgency, cost, risk and impact; approves in stages and feeds back lessons learned.', eg:'A CAB pauses a rollout at an approval stage until a security issue is fixed.', exam:'Name a CAB benefit (prioritising/risk-checking changes) in change-management answers.' },
  { area:'CO5', term:'SMARTER objectives', def:'A way to set change objectives: Specific, Measurable, Achievable, Realistic, Time-bound, Evaluate, Revise.', tech:'Turns a vague goal into a trackable one with a deadline and review built in.', eg:'"Increase online sales from £50k to £65k within 6 months, then review."', exam:'Recall what each letter means; "Evaluate" and "Revise" are the two often forgotten.' },
  { area:'CO5', term:'Feasibility (TELOS)', def:'Whether a project is viable: Technical, Economic, Legal, Operational, Schedule.', tech:'A business case weighs costs, benefits and risks across these dimensions before approval.', eg:'A new system may be technically possible but fail economic feasibility (poor ROI).', exam:'Identify which feasibility a scenario is testing (e.g. "can we afford it?" = economic).' },
  { area:'CO5', term:'Audience exclusion', def:'When some users are shut out of a digital service (lack of internet, skills, devices, or biased/poor design).', tech:'A risk of digitising services; can also arise from biased algorithms or jargon-heavy interfaces.', eg:'Closing bank branches excludes older customers without online-banking skills.', exam:'A frequent "risk of digital systems" answer — link it to lost customers/legal risk.' },
  { area:'CO5', term:'Reputational damage', def:'Loss of public trust after a failure/breach, often amplified on social media.', tech:'Hard to quantify but can cause lost customers, falling share price and reduced business.', eg:'A retailer\'s share price drops after a publicised cyberattack.', exam:'A key "impact" of risks — pair it with fines, legal action and loss of business.' },

  /* ---------------- CO6 ---------------- */
  { area:'CO6', term:'Automation', def:'Using machines/software to perform tasks with little human input.', tech:'Boosts productivity and consistency but can displace routine jobs and demands reskilling.', eg:'Self-checkouts automate cashier tasks, reducing staffing needs.', exam:'Discuss both efficiency gains AND job-loss/morale impacts for balanced marks.' },
  { area:'CO6', term:'Artificial Intelligence (AI)', def:'Systems that perform tasks normally needing human intelligence (pattern recognition, decisions).', tech:'Underpins recommendations, fraud detection and chatbots; risks include bias, privacy and over-reliance.', eg:'A bank uses AI to flag suspicious transactions in real time.', exam:'Be ready to give one benefit AND one drawback of AI to an organisation.' },
  { area:'CO6', term:'Generative AI', def:'AI that creates new content — text, images, audio, video or code.', tech:'Trained on large datasets; powerful for productivity but can produce deepfakes and misinformation.', eg:'ChatGPT drafts emails; DALL·E generates images from prompts.', exam:'Distinguish generative AI (creates content) from machine learning (learns patterns).' },
  { area:'CO6', term:'Machine learning', def:'Systems that learn patterns from data and improve over time without explicit programming.', tech:'Includes deep learning (multi-layer neural networks); used in image/speech recognition and prediction.', eg:'A spam filter that gets better as it sees more example emails.', exam:'Often paired with AI bias — biased training data → unfair outputs.' },
  { area:'CO6', term:'Quantum computing', def:'Computing using qubits (0, 1 or both at once) to solve certain problems far faster than classical computers.', tech:'Exploits superposition and entanglement; could break current encryption, aid drug discovery and optimisation — but is early-stage, error-prone and needs near-absolute-zero temperatures.', eg:'A quantum computer could in theory brute-force encryption in minutes that would take a classic computer years.', exam:'"One way quantum computing could impact an organisation" → decreased security (breaking encryption) or faster problem-solving.' },
  { area:'CO6', term:'Internet of Things (IoT)', def:'Everyday devices connected to the internet so they can be monitored or controlled remotely.', tech:'Enabled by 5G; major risk is weak default passwords and the lack of global security standards.', eg:'A smart thermostat or fridge controlled from a phone app.', exam:'State an IoT security risk (weak passwords → entry point to the network).' },
  { area:'CO6', term:'Edge computing', def:'Processing data close to where it is generated rather than in a central cloud.', tech:'Reduces latency and reliance on the internet but adds more devices to secure.', eg:'A smart doorbell detecting motion and streaming locally without a round trip to the cloud.', exam:'Contrast with cloud computing (central) — edge = local, low latency.' },
  { area:'CO6', term:'Digital inclusion', def:'Ensuring everyone can access and use digital services regardless of income, skills, location or disability.', tech:'Addressed via affordable/assistive technology, connectivity, dataset-bias checks and accessibility regulations.', eg:'Providing rural broadband and assistive tools so more people can access online services.', exam:'Links to audience exclusion (CO5) — name a way to improve inclusion.' },
  { area:'CO6', term:'AI bias', def:'When AI produces unfair outcomes because its training data was unrepresentative or reflected past bias.', tech:'Mitigated with anti-bias training, representative data and human oversight.', eg:'A hiring AI favouring male candidates because it was trained mostly on men\'s CVs.', exam:'A strong evaluation point for AI questions — note the mitigation (human oversight).' },

  /* ---------------- CO7 ---------------- */
  { area:'CO7', term:'Server', def:'A powerful computer providing shared resources/security to many users on a network.', tech:'Built for reliability with redundant power supplies, multiple NICs and RAID drives; can be local or cloud-hosted.', eg:'A file server stores shared documents and manages staff logins.', exam:'Justify a server over a desktop with redundancy/shared access.' },
  { area:'CO7', term:'RAM vs ROM', def:'RAM is fast, volatile working memory; ROM is non-volatile memory holding start-up firmware.', tech:'RAM loses its contents at power-off and speeds up the running program; ROM keeps the BIOS/UEFI needed to boot.', eg:'Open apps live in RAM; the boot firmware lives in ROM.', exam:'"State two differences between RAM and ROM" is a classic 2-marker.' },
  { area:'CO7', term:'LAN / WAN / VPN', def:'LAN covers one site; WAN spans large areas (the internet is the biggest WAN); a VPN is a secure encrypted tunnel over the internet.', tech:'VPNs protect data on public/home Wi-Fi from man-in-the-middle interception.', eg:'A remote worker uses a VPN to reach the office network securely from a café.', exam:'Match the network type to the scenario\'s scale; VPN = secure remote access.' },
  { area:'CO7', term:'Router vs Switch', def:'A router connects a network to the internet and directs external traffic; a switch connects devices within a LAN.', tech:'Home hubs combine a router, switch and wireless access point; routers often include a firewall.', eg:'A switch links office PCs and printers; the router sends their traffic out to the internet.', exam:'Don\'t mix them up — router = to the internet, switch = within the LAN.' },
  { area:'CO7', term:'Star topology', def:'A layout where every device connects to a central switch.', tech:'Easy fault-finding and a single device failure doesn\'t affect others, but the central switch is a single point of failure and it uses lots of cable.', eg:'A typical office network with all PCs cabled to one switch.', exam:'Evaluate it: easy to maintain/secure vs single point of failure (add a backup switch).' },
  { area:'CO7', term:'Bandwidth vs Latency', def:'Bandwidth = maximum data per second; latency = the delay before data arrives.', tech:'Max bandwidth is limited by the slowest link; total latency is the sum of all hop delays (ms).', eg:'A fast fibre line (high bandwidth) can still feel slow if a distant server adds high latency.', exam:'Define each precisely and give the units (bps vs ms).' },
  { area:'CO7', term:'Mail protocols (SMTP/POP3/IMAP)', def:'SMTP sends mail; POP3 downloads it to one device; IMAP keeps it on the server and syncs across devices.', tech:'IMAP suits multi-device users; POP3 suits single-device use and frees server storage.', eg:'Your phone and laptop both show the same inbox because the account uses IMAP.', exam:'"Explain two mail protocols other than SMTP" → POP3 and IMAP with a use each.' },
  { area:'CO7', term:'Virtual machine & hypervisor', def:'A VM is a software emulation of a computer; a hypervisor creates and manages VMs on a host.', tech:'Type 1 (bare-metal) is fastest; Type 2 runs on a host OS. Isolation means one VM\'s crash/compromise doesn\'t affect others.', eg:'One physical server runs several isolated virtual servers for different services.', exam:'Use isolation/portability/snapshots to argue VMs over physical machines.' },
  { area:'CO7', term:'Cloud models (IaaS/PaaS/SaaS)', def:'Layers of cloud service: IaaS (infrastructure), PaaS (platform), SaaS (whole application).', tech:'The further down the list, the more the provider manages and the less the customer does (and customises).', eg:'AWS EC2 (IaaS), a managed app platform (PaaS), Office 365 online (SaaS).', exam:'Know who manages what; SaaS = customer only manages accounts/data.' },
  { area:'CO7', term:'Elasticity', def:'A cloud environment automatically scaling resources up or down to match demand.', tech:'Lets a business pay for peak capacity only when needed, ideal for spiky workloads.', eg:'A retailer scales servers up for Black Friday then back down afterwards.', exam:'A key cloud benefit for variable-demand scenarios.' },
  { area:'CO7', term:'RAID & redundancy', def:'RAID stores data across multiple drives for redundancy/performance; redundancy = spare components so the system keeps running on failure.', tech:'RAID 1 mirrors data so a single drive failure loses nothing; servers add dual PSUs, UPS and multiple NICs.', eg:'A failed RAID drive is hot-swapped while the server keeps running.', exam:'RAID protects against drive failure but NOT fire/theft/ransomware — pair with off-site backups.' },
  { area:'CO7', term:'Device hardening', def:'Securing a device by reducing its vulnerabilities and enforcing strict access controls.', tech:'Updates/patches, disabling unused services/ports, encryption, unique logins, host antivirus and configured firewalls.', eg:'Closing unused ports and enabling auto-updates on a server.', exam:'"One benefit of device hardening" → reduces the attack surface, making access harder.' },

  /* ---------------- CO8 ---------------- */
  { area:'CO8', term:'Confidentiality, Integrity, Availability (CIA triad)', def:'The three core goals of security: keep data private, unaltered and accessible.', tech:'They interrelate — maintaining confidentiality supports integrity, which supports availability; all three are needed for real security.', eg:'Encryption protects confidentiality; backups protect availability; access controls protect integrity.', exam:'"What is meant by confidentiality?" → keeping data private by controlling access.' },
  { area:'CO8', term:'IAAA model', def:'Identification → Authentication → Authorisation → Accountability.', tech:'Identify (username) → verify (password/biometric/MFA) → limit access (role-based/ACL) → trace actions (audit logs).', eg:'A hospital logs which clinician viewed each patient record (accountability).', exam:'Distinguish authentication (prove identity) from authorisation (what you may do).' },
  { area:'CO8', term:'Threat vs Vulnerability', def:'A threat is something that could cause harm; a vulnerability is a weakness that lets it succeed.', tech:'A threat (e.g. a hacker) exploits a vulnerability (e.g. weak password/no MFA) to cause an impact.', eg:'Phishing (threat) succeeds because of untrained staff (vulnerability).', exam:'Classify items correctly — "weak password policy" is a vulnerability, "malware" is a threat.' },
  { area:'CO8', term:'Malware', def:'Malicious software designed to damage, disrupt or gain unauthorised access.', tech:'Includes viruses, worms, keyloggers, ransomware, spyware and remote-access trojans; mitigated by anti-malware, updates and backups.', eg:'Ransomware encrypts a company\'s files and demands payment to unlock them.', exam:'Be able to name several types and one mitigation each.' },
  { area:'CO8', term:'Social engineering (phishing family)', def:'Tricking people into revealing information or access.', tech:'Phishing (email), spear phishing (targeted), smishing (SMS), vishing (voice), pharming, USB baiting; countered by training and MFA.', eg:'A fake "reset your password" email harvesting staff credentials.', exam:'Identify the variant from the channel (text=smishing, call=vishing).' },
  { area:'CO8', term:'Denial of Service (DoS/DDoS)', def:'Flooding a system with traffic so it becomes unavailable (DDoS = from many machines/a botnet).', tech:'Mitigated with firewalls, intrusion prevention, rate limiting and load balancers/redundancy.', eg:'An attacker overwhelms a website so genuine customers can\'t reach it.', exam:'Mainly harms Availability (CIA) — name a mitigation method.' },
  { area:'CO8', term:'Firewall configuration', def:'A firewall controls network traffic using rules to allow or block it.', tech:'Rules can be based on IP address, traffic type (ports/protocols), application, and direction (inbound/outbound).', eg:'Blocking inbound traffic from a known-malicious IP range.', exam:'"Two ways a firewall controls incoming traffic" → IP-address rules and port/protocol rules.' },
  { area:'CO8', term:'Encryption (symmetric, asymmetric, hashing)', def:'Scrambling data so only authorised parties can read it.', tech:'Symmetric uses one shared key (fast); asymmetric uses a public/private key pair; hashing is one-way (used for passwords).', eg:'HTTPS encrypts web traffic; password databases store hashes, not plain text.', exam:'Hashing is one-way (not reversible) — a common distinguishing point.' },
  { area:'CO8', term:'Multi-factor authentication (MFA)', def:'Requiring two or more independent proofs of identity to log in.', tech:'Combines something you know (password), have (phone/token) or are (biometric); blocks stolen-password logins.', eg:'Logging in needs a password plus a one-time code from an app.', exam:'A high-value mitigation — even a stolen password isn\'t enough.' },
  { area:'CO8', term:'Penetration testing', def:'Authorised (ethical) hacking to find vulnerabilities before attackers do.', tech:'Simulates real attacks; unethical hacking is the same activity without permission (illegal).', eg:'A firm hires testers to attack its own site and report the holes.', exam:'Note the ethical vs unethical distinction (authorised vs not).' },
  { area:'CO8', term:'Poor cyber hygiene', def:'Careless user habits that create security vulnerabilities.', tech:'Examples: leaving machines unlocked, writing passwords down, poor password management; fixed by locking screens, password managers and training.', eg:'A sticky note with a password on a monitor in a public office.', exam:'"One way to protect against poor cyber hygiene" → lock unattended machines / don\'t write passwords down.' },
  { area:'CO8', term:'Disguised criminal / tailgating / shoulder surfing', def:'Physical/human threats: pretending to be staff, following someone through a secure door, or watching them enter data.', tech:'Countered by accompanying visitors, checking ID, anti-tailgating doors, privacy screens and awareness training.', eg:'A "contractor" with no ID is escorted at all times to prevent free roaming.', exam:'"Prevent a disguised criminal" → accompany visitors and check identification.' }
];
